name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
          cache: "pip"
          cache-dependency-path: pyproject.toml

#  TODO: fix it later
#      - uses: actions/cache@v3
#        id: cache
#        with:
#          path: ${{ env.pythonLocation }}
#          key: ${{ runner.os }}-python-${{ env.pythonLocation }}-${{ hashFiles('pyproject.toml') }}-test-v03

      - name: Install Dependencies
#        if: steps.cache.outputs.cache-hit != 'true'
        run: make install

      - name: Lint
        run: make lint
